### ISSUE TITLE
usage of gravo in docker compose

### ISSUE THREAD

**Issue by muc-patrick** [andig/gravo#13]
Hi *,

short question from my side.
How can I address the api to the middleware by using docker compose? 
I haven't find any way, see below my docker-compose.yml:

`Service:
...

volkszaehler:
    image: volkszaehler/volkszaehler
    ports:
    - 8079:8080
    # NOTE: The init command will only work once the database is fully up and running.
    #       By putting restart: always docker-compose will retry starting this container
    #       and finally complete the database setup sequence.
    command: sh -c "
      sed -i s/localhost/database/ /vz/etc/config.yaml &&
      sed -i s/vz_admin/root/ /vz/etc/config.yaml &&
      sleep 1 &&
      (/vz/bin/doctrine orm:schema-tool:update --force || /vz/bin/doctrine orm:schema-tool:create) &&
      /vz/vendor/bin/ppm start -c /vz/etc/middleware.json --static-directory /vz/htdocs --cgi-path=/usr/local/bin/php"
    links:
    - database
    depends_on:
    - database
    networks:
    - volkszaehler
    restart: always

  gravo:
    image: andig/gravo
    ports:
     - 8000:8000
    command:
     - -api http://ip:8080
    links:
    - volkszaehler
    networks:
    - volkszaehler
    restart: always

...
`

**Comment by psych0d0g** [comment]
```
  gravo:
    image: andig/gravo
    ports:
    - 8000:8000
    entrypoint: [/usr/bin/gravo, -api, http://volkszaehler:8080]
    links:
    - volkszaehler
    depends_on:
    - volkszaehler
    networks:
    - volkszaehler
    restart: always
```

that way it works for me
